spring.application.name=solar-watch

spring.datasource.url=jdbc:postgresql://localhost:5432/solarwatch
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openweather.api.key=${OPENWEATHER_API_KEY}
openweather.geocoding.url=https://api.openweathermap.org/geo/1.0/direct

sunrise.api.url=https://api.sunrise-sunset.org/json

# Server Configuration
server.port=8080

# JWT Double Secret Keys
jwt.access-token-secret=/JcSBU2TUSy4Sf32sDediQZuLQL/zrsUDoWIxLaB3rYYF+jjftCDjmABmxmGg6NVVaVIKGfq+J0OnCEA0T5leA==
jwt.refresh-token-secret=7ldnOR2nfsQ1fP9W+fj70//V9h//oe4DX4/DD3CAMF/mFVhXazOf5Bw2b8Fh6x0WRuyjOPxREzA29lT58aWh8w==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000